### ISSUE TITLE
Running the examples raises an exception at `shell.Show()`

### ISSUE THREAD

**Issue by bigworld12** [WildGums/Orchestra#146]
# Steps to reproduce

1. Clone the repo
2. rebuild and run any example project `Orchestra.Examples.MahApps`

Platform: win 10
.NET version: core 3.0.100-preview5-011568

### Expected behaviour

should run normally

### Actual behaviour

raises the following exception at `shell.Show()`

Log:
```
Orchestra.Examples.MahApps Error: 0 : 14:00:54:582 => [ERROR] [Orchestra.LogHelper] [1] Application crashed | [FormatException] System.FormatException: Format string is incorrect. Month field must be in one of formats: 'M' or 'MM'
   at Orc.Controls.DateTimeFormatInfoExtensions.SetMonthFormat(DateTimeFormatInfo formatInfo, String part, Int32 position) in C:\CI_WS\Ws\128887\Source\Orc_Controls\src\Orc.Controls\Extensions\DateTimeFormatInfoExtensions.cs:line 140
   at Orc.Controls.DateTimeFormatInfoExtensions.FormatPart(DateTimeFormatInfo result, String part, Int32 current, Boolean isDateOnly) in C:\CI_WS\Ws\128887\Source\Orc_Controls\src\Orc.Controls\Extensions\DateTimeFormatInfoExtensions.cs:line 61
   at Orc.Controls.DateTimeFormatHelper.GetDateTimeFormatInfo(String format, Boolean isDateOnly) in C:\CI_WS\Ws\128887\Source\Orc_Controls\src\Orc.Controls\Helpers\DateTimeFormatHelper.cs:line 81
   at Orc.Controls.DatePicker.ApplyFormat() in C:\CI_WS\Ws\128887\Source\Orc_Controls\src\Orc.Controls\Controls\DatePicker\Views\DatePicker.xaml.cs:line 389
   at Orc.Controls.DatePicker.OnLoaded(EventArgs e) in C:\CI_WS\Ws\128887\Source\Orc_Controls\src\Orc.Controls\Controls\DatePicker\Views\DatePicker.xaml.cs:line 351
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Orchestra.Examples.MahApps Information: 0 : 14:00:54:605 => [INFO] [Orchestra.DotNetPatchHelper] [1] An unhandled exception occurred, checking if it is a known KB issue: Format string is incorrect. Month field must be in one of formats: 'M' or 'MM'
Orchestra.Examples.MahApps Information: 0 : 14:00:54:609 => [INFO] [Orchestra.DotNetPatchHelper] [1] Below is a list of the last first chance exceptions that occurred. It might provide more information to the issue.
Orchestra.Examples.MahApps Information: 0 : 14:00:54:612 => [INFO] [Orchestra.DotNetPatchHelper] [1] ================================================================================================
Orchestra.Examples.MahApps Information: 0 : 14:00:54:616 => [INFO] [Orchestra.DotNetPatchHelper] [1] 
Orchestra.Examples.MahApps Information: 0 : 14:00:54:623 => [INFO] [Orchestra.DotNetPatchHelper] [1] [FileNotFoundException] System.IO.FileNotFoundException: Could not load file or assembly 'Catel.MVVM.Aero2, Version=5.10.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Catel.MVVM.Aero2, Version=5.10.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Windows.SystemResources.ResourceDictionaries.LoadExternalAssembly(Boolean classic, Boolean generic, Assembly& assembly, String& assemblyName)


Orchestra.Examples.MahApps Information: 0 : 14:00:54:627 => [INFO] [Orchestra.DotNetPatchHelper] [1] 
Orchestra.Examples.MahApps Information: 0 : 14:00:54:631 => [INFO] [Orchestra.DotNetPatchHelper] [1] ================================================================================================
Orchestra.Examples.MahApps Information: 0 : 14:00:54:635 => [INFO] [Orchestra.DotNetPatchHelper] [1] 
Orchestra.Examples.MahApps Information: 0 : 14:00:54:640 => [INFO] [Orchestra.DotNetPatchHelper] [1] [NotSupportedException] System.NotSupportedException: ImageSourceConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
```

**Comment by GeertvanHorrik** [comment]
Seems to work here:

![image](https://user-images.githubusercontent.com/1246444/60183459-a96a3580-9826-11e9-91bf-88be59681792.png)

Maybe it's culture related? As you can see, it might be coming from Orc.Controls (DatePicker control).

**Comment by bigworld12** [comment]
i thought so too, but i am using us culture, i am not sure what's wrong here

**Comment by bigworld12** [comment]
ok so i did some debugging and found out where the problem is, i moved this issue to https://github.com/WildGums/Orc.Controls/issues/91
