### ISSUE TITLE
MahApps theme exception

### ISSUE THREAD

**Issue by abrca** [WildGums/Orchestra#276]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] WPF
 - [X] .NET Standard
 - [X] .NET Core

## Component

What component is this issue occurring in?
Orchestra.Examples.MahApps 

## Version of Library
Fresh from GitHub

## Version of OS(s) listed above with issue
Windows 10 x64

## Steps to Reproduce
1. Compile and run Orchestra.Examples.MahApps 
2. Catch exception after startup windows

## Expected Behavior
Working

## Actual Behavior

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message="Предоставление значения для "System.Windows.Markup.StaticResourceHolder" вызвало исключение.": номер строки "175" и позиция в строке "12".
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.ResourceDictionaryEnumerator.System.Collections.IDictionaryEnumerator.get_Entry()
   at System.Windows.ResourceDictionary.ResourceDictionaryEnumerator.System.Collections.IEnumerator.get_Current()
   at ControlzEx.Theming.Theme.GetValueFromKey(ResourceDictionary resourceDictionary, Object key)
   at ControlzEx.Theming.Theme.GetThemeInstance(ResourceDictionary resourceDictionary)
   at ControlzEx.Theming.Theme.GetThemeName(ResourceDictionary resourceDictionary)
   at ControlzEx.Theming.Theme.IsThemeDictionary(ResourceDictionary resourceDictionary)
   at ControlzEx.Theming.Theme.IsRuntimeGeneratedThemeDictionary(ResourceDictionary resourceDictionary)
   at ControlzEx.Theming.ThemeManager.GetTheme(ResourceDictionary resourceDictionary)
   at ControlzEx.Theming.ThemeManager.DetectThemeFromResources(ResourceDictionary dict, Theme& detectedTheme)
   at ControlzEx.Theming.ThemeManager.DetectThemeFromResources(ResourceDictionary dict, Theme& detectedTheme)
   at ControlzEx.Theming.ThemeManager.DetectTheme(ResourceDictionary resourceDictionary)
   at ControlzEx.Theming.ThemeManager.ChangeTheme(Object target, ResourceDictionary resourceDictionary, Theme newTheme)
   at ControlzEx.Theming.ThemeManager.ChangeTheme(Application app, Theme newTheme)
   at Orchestra.Theming.ThemeManager.ChangeTheme(Theme generatedTheme) in D:\DEV\Orchestra-develop\src\Orchestra.Core\Theming\Managers\ThemeManager.cs:line 66

  This exception was originally thrown at this call stack:
	System.Windows.StaticResourceExtension.ProvideValueInternal(System.IServiceProvider, bool)
	System.Windows.StaticResourceExtension.ProvideValue(System.IServiceProvider)
	MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)

Inner Exception 1:
Exception: Не удается найти ресурс с именем "MahApps.Styles.ValidationPopup". Имена ресурсов определяются с учетом регистра.

**Comment by GeertvanHorrik** [comment]
Fixed, thanks for reporting!

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, will try to fix this one!

@abrca can you please contact me via geert [at] catenalogic [com]?

**Comment by GeertvanHorrik** [comment]
Also fixing the default styles handling (much simplified now), and MahApps style will be the default when using the MahApps shell:

![image](https://user-images.githubusercontent.com/1246444/80979418-9bfae000-8e27-11ea-9630-270442499e45.png)
