### ISSUE TITLE
Examples.TaskRunner exception

### ISSUE THREAD

**Issue by abrca** [WildGums/Orchestra#279]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [x] .NET Standard

## Component
What component is this issue occurring in?
Orchestra.Examples.TaskRunner 

## Version of Library
Fresh from GitHub

## Version of OS(s) listed above with issue
Windows 10 x64

## Steps to Reproduce
1. Compile and run Orchestra.Examples.TaskRunner 
2. After Loading window, catch the exception

## Expected Behavior
Normal startup

## Actual Behavior
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Сообщение = Предоставление значения для "System.Windows.StaticResourceExtension" вызвало исключение.
  Источник = PresentationFramework
  Трассировка стека:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Orchestra.Views.ShellWindow.InitializeComponent() in D:\DEV\orc\Orchestra-develop\src\Orchestra.Shell.TaskRunner\Views\ShellWindow.xaml:line 1

  Изначально это исключение было создано в этом стеке вызовов:
	System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(System.Windows.Baml2006.Baml2006SchemaContext.BamlType, short)
	System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(short)
	System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
	System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
	System.Windows.Baml2006.Baml2006Reader.ReadObject(System.Windows.Baml2006.KeyRecord)
	System.Windows.ResourceDictionary.CreateObject(System.Windows.Baml2006.KeyRecord)
	System.Windows.ResourceDictionary.OnGettingValue(object, ref object, out bool)
	System.Windows.ResourceDictionary.OnGettingValuePrivate(object, ref object, out bool)
	System.Windows.ResourceDictionary.GetValueWithoutLock(object, out bool)
	System.Windows.ResourceDictionary.GetValue(object, out bool)
    ...
    [Стек вызовов обрезан]
Внутреннее исключение 1:
NotImplementedException: The method or operation is not implemented.

**Comment by GeertvanHorrik** [comment]
Should be fixed.
