### ISSUE TITLE
Ugly exceptions in the Orchestra.Examples.Ribbon.Microsoft.Net45 runtime

### ISSUE THREAD

**Issue by auz34** [WildGums/Orchestra#36]
Found In: version 2.2.0

There are two places in main window where exception is thrown

#### XamlParseException
Steps to reproduce:
1. Built and run  Orchestra.Examples.Ribbon.Microsoft.Net45 project;
2. In main menu click on "Shortcuts" menu item.

#### TargetInvocationException
Steps to reproduce:
1. Built and run  Orchestra.Examples.Ribbon.Microsoft.Net45 project;
2. In main menu click on question icon (right top corner)

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. Will look into this now.

**Comment by GeertvanHorrik** [comment]
I can reproduce the TargetInvocationException.

**Comment by GeertvanHorrik** [comment]
It was a missing icon.

**Comment by GeertvanHorrik** [comment]
Fixed, now looking into the XamlParseException.

**Comment by GeertvanHorrik** [comment]
I can't reproduce the XamlParseException. Can you specify the line / column where this exception occurs?

**Comment by auz34** [comment]
It appeared to me that Shortcuts button has two parts. In order to reproduce the issue we need to click on the lower one.

Stack trace is only one line so screenshot will be more informative:
![image](https://cloud.githubusercontent.com/assets/3331375/9828745/e2b6f2ba-58a6-11e5-8720-5b896d5f2fc6.png)

Let me know whether you need more help with this.

**Comment by GeertvanHorrik** [comment]
Thanks for the details. Can you try cleaning your output directory and doing a full build? I can't seem to reproduce this.

**Comment by auz34** [comment]
Previously reported events happened under Windows Server 2008 R2. Under Windows 7 the same steps  produce different exception and stack (see below).
Also I will send you video by mail 
   at System.Windows.Controls.Primitives.Popup.OnWindowResize(Object sender, AutoResizedEventArgs e)
   at System.Windows.Interop.HwndSource.Resize(Size newSize)
   at System.Windows.Interop.HwndSource.OnLayoutUpdated(Object obj, EventArgs args)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Orchestra.Examples.Ribbon.App.Main() in d:\_OpenSource\Orchestra2\src\Examples\Orchestra.Examples.Ribbon.Microsoft\Orchestra.Examples.Ribbon.Microsoft.NET45\obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)999
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)9999999
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by GeertvanHorrik** [comment]
My mistake. I used the Fluent ribbon shell instead of the Ms one (and honestly, you want that too).

**Comment by auz34** [comment]
>> and honestly, you want that too
Anything particular?

P.S. Honestly, I don't remember details what was wrong with Fluent back in late 2013 when I was comparing Fluent and MS and started to prefer MS over Fluent.

**Comment by GeertvanHorrik** [comment]
Fluent was no longer in maintenance at that time. But it's picked up and actively being developed (all our apps use it, it looks much, much better than the ms one). Still fixing the issue though.

**Comment by GeertvanHorrik** [comment]
All fixed, thanks for reporting, we really appreciate that.

**Comment by GeertvanHorrik** [comment]
Closing issue. Feel free to re-open when it still doesn't work for you.

**Comment by auz34** [comment]
Great! I can confirm it works for me now
