### ISSUE TITLE
try to run examples, run into nullreferenceException

### ISSUE THREAD

**Issue by psc0425** [WildGums/Orchestra#45]
this is from vs2015

System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=MahApps.Metro
  StackTrace:
       at MahApps.Metro.ThemeManager.ChangeAppStyle(ResourceDictionary resources, Tuple`2 oldThemeInfo, Accent newAccent, AppTheme newTheme) in C:\Users\punker76\Documents\GitHub\MahApps.Metro\MahApps.Metro\ThemeManager.cs:line 369
       at MahApps.Metro.ThemeManager.ChangeAppStyle(Application app, Accent newAccent, AppTheme newTheme) in C:\Users\punker76\Documents\GitHub\MahApps.Metro\MahApps.Metro\ThemeManager.cs:line 342
       at Orchestra.MahAppsHelper.ApplyTheme() in C:\Users\phils\Documents\github\Orchestra\src\Orchestra.Shell\Orchestra.Shell.MahApps\Orchestra.Shell.MahApps.Shared\Helpers\MahAppsHelper.cs:line 73
       at Orchestra.Views.ShellWindow..ctor() in C:\Users\phils\Documents\github\Orchestra\src\Orchestra.Shell\Orchestra.Shell.MahApps\Orchestra.Shell.MahApps.Shared\Views\ShellWindow.xaml.cs:line 35
  InnerException: 

I was trying to run:
Orchestra.Examples.MahApps.Net45

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. We are aware of this issue, it's caused by a recent update of MahApps. We are actively looking into this.

**Comment by psc0425** [comment]
Thanks for the update.

**Comment by GeertvanHorrik** [comment]
We are now tracking this issue internally, we hope to fix this for the upcoming stable release of Orchestra.
