### ISSUE TITLE
Orchestra.Examples.MahApps does not work

### ISSUE THREAD

**Issue by IvanGit** [WildGums/Orchestra#950]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [+ ] WPF
 - [ ] Blazor WASM
 - [ ] .NET Core

## Component

What component is this issue occurring in?
[Orchestra](https://github.com/WildGums/Orchestra)

## Version of Library

Latest

## Version of OS(s) listed above with issue

Win 10

## Steps to Reproduce
1. Clone repo
2. Select Orchestra.Examples.MahApps as statup
3. Run

## Expected Behavior

Working example

## Actual Behavior

```System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message="Задание свойства "System.Windows.ResourceDictionary.Source" вызвало исключение.": номер строки "15" и позиция в строке "10".
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverterCore(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStreamCore(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at Orchestra.Examples.MahApps.Services.MaterialDesignXamlResourceService.GetApplicationResourceDictionaries() in C:\DEV\MyProjects\3rdPartyProjects\Orchestra\src\Orchestra.Examples.MahApps\Services\MaterialDesignXamlResourceService.cs:line 29

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
IOException: Не удается найти ресурс "themes/materialdesigntheme.defaults.xaml".
```

**Comment by GeertvanHorrik** [comment]
After some consideration, we created this PR:

https://github.com/WildGums/Orchestra/pull/954

I consider the chance of this being fixed near to zero.
